### ISSUE TITLE
I use vs2022 to compile on win10 64, quite a few errors, mainly character encryption macros, the previous version can be compiled smoothly

### ISSUE THREAD

**Issue by icyfox168168** [AmJayden/custom-VEH#2]
。

**Comment by icyfox168168** [comment]
#define ud_xorstr( str ) std::string_view{ ud_xorstr_c( str ) }

**Comment by AmJayden** [comment]
Are you using the v143 toolset? And C++20?

**Comment by icyfox168168** [comment]
Use your default settings, there is no compilation problem in the last version, how do you need to set it?

**Comment by AmJayden** [comment]
🤦 the issue was that I pushed it with a typo lol, let me fix it right now

**Comment by AmJayden** [comment]
pushed, here's it compiling on the latest version on github
![image](https://user-images.githubusercontent.com/53480580/171205510-18fdeec5-dac8-4b00-bf37-c99174885f92.png)
